import AsyncStorage from "@react-native-async-storage/async-storage";
import { wipeDatabase } from "./database";
import { supabase } from "./supabase";
import { cacheSession, clearSessionCache } from "./session-cache";


export async function signIn(email: string, password: string) {
  const { data, error } = await supabase.auth.signInWithPassword({
    email,
    password,
  });

  if (error) {
    throw error;
  }

  // Cache session for offline access
  if (data.user && data.session) {
    await cacheSession(data.user.id, data.user.email!, data.session.access_token);
  }

  return data;
}

/**
 * Standard signup function with profile metadata.
 * Uses Supabase's built-in OTP system. 
 * OTP will be generated by Supabase and sent via the 'Send Email' auth hook.
 */
export async function registerWithProfile(
  email: string,
  password: string,
  fullName: string,
  phoneNumber: string,
  businessType: string
) {
  const { data, error } = await supabase.auth.signUp({
    email,
    password,
    options: {
      data: {
        full_name: fullName.trim(),
        phone_number: phoneNumber.trim(),
        business_type: businessType,
      },
    },
  });

  if (error) {
    throw error;
  }

  if (!data.user) {
    throw new Error("Failed to create user account");
  }

  // Cache session for offline access
  const { data: { session } } = await supabase.auth.getSession();
  if (data.user && session) {
    await cacheSession(data.user.id, data.user.email!, session.access_token);
  }

  return {
    user: data.user,
    profileData: {
      fullName,
      phoneNumber,
      businessType,
    },
  };
}

export async function signOut() {
  const { error } = await supabase.auth.signOut();

  // Full data wipe on logout
  try {
    await clearSessionCache();
    await wipeDatabase();
    await AsyncStorage.clear();
  } catch (e) {
    console.error("Error wiping local data during logout:", e);
  }

  if (error) {
    throw error;
  }
}

/**
 * Initiates password reset process.
 * Supabase will generate a recovery token and send it via the 'Send Email' auth hook.
 */
export async function forgotPassword(email: string) {
  const { data, error } = await supabase.auth.resetPasswordForEmail(email, {
    redirectTo: undefined, // Let the app handle it instead of deep links
  });

  if (error) {
    throw error;
  }

  return data;
}

/**
 * Updates the password for the current session user.
 */
export async function updatePassword(newPassword: string) {
  const { data, error } = await supabase.auth.updateUser({
    password: newPassword,
  });

  if (error) {
    throw error;
  }

  return data;
}