import AsyncStorage from "@react-native-async-storage/async-storage";
import { wipeDatabase } from "./database";
import { supabase } from "./supabase";
import { cacheSession, clearSessionCache } from "./session-cache";
import { clearProfileCache, cacheProfile } from "./profile-cache";


export async function signIn(email: string, password: string) {
  const { data, error } = await supabase.auth.signInWithPassword({
    email,
    password,
  });

  if (error) {
    throw error;
  }

  // Cache session for offline access
  if (data.user && data.session) {
    await cacheSession(data.user.id, data.user.email!, data.session.access_token);
    
    // Load and cache profile immediately after login
    try {
      const { data: profileData } = await supabase
        .from("profiles")
        .select("*")
        .eq("id", data.user.id)
        .single();
      
      if (profileData) {
        await cacheProfile({
          id: profileData.id,
          full_name: profileData.full_name,
          email: profileData.email,
          phone_number: profileData.phone_number,
          business_type: profileData.business_type,
        });
        console.log('[Auth] Profile loaded and cached on login');
      }
    } catch (profileError) {
      console.log('[Auth] Could not load profile on login (non-blocking):', profileError);
    }

    // Trigger initial sync to download data from server
    // CRITICAL: Wait for sync to complete before returning
    // This ensures categories and transactions are available immediately
    try {
      console.log('[Auth] Starting initial sync after login (blocking)...');
      const { SyncEngine } = await import('./offline/sync/SyncEngine');
      const syncEngine = new SyncEngine(data.user.id);
      const result = await syncEngine.sync();
      console.log('[Auth] Initial sync completed:', JSON.stringify(result, null, 2));
      
      if (result.success) {
        console.log(`[Auth] ✅ Sync successful - Downloaded ${result.downloadedCount} items, Uploaded ${result.uploadedCount} items`);
      } else {
        console.log(`[Auth] ⚠️ Sync had ${result.errors.length} errors:`, result.errors);
      }
      
      // Verify categories were downloaded
      const { getUserCategories } = await import('./categories');
      const categories = await getUserCategories();
      console.log(`[Auth] Categories in local database after sync: ${categories.length} items`);
      if (categories.length > 0) {
        console.log('[Auth] First 3 categories:', categories.slice(0, 3).map(c => c.name));
      }
    } catch (syncError) {
      console.error('[Auth] ❌ Initial sync failed:', syncError);
    }
  }

  return data;
}

/**
 * Standard signup function with profile metadata.
 * Uses Supabase's built-in OTP system. 
 * OTP will be generated by Supabase and sent via the 'Send Email' auth hook.
 */
export async function registerWithProfile(
  email: string,
  password: string,
  fullName: string,
  phoneNumber: string,
  businessType: string
) {
  const { data, error } = await supabase.auth.signUp({
    email,
    password,
    options: {
      data: {
        full_name: fullName.trim(),
        phone_number: phoneNumber.trim(),
        business_type: businessType,
      },
    },
  });

  if (error) {
    throw error;
  }

  if (!data.user) {
    throw new Error("Failed to create user account");
  }

  // Cache session for offline access
  const { data: { session } } = await supabase.auth.getSession();
  if (data.user && session) {
    await cacheSession(data.user.id, data.user.email!, session.access_token);
    
    // Cache profile data from metadata for immediate availability
    await cacheProfile({
      id: data.user.id,
      full_name: fullName.trim(),
      email: email,
      phone_number: phoneNumber.trim(),
      business_type: businessType,
    });
    console.log('[Auth] Profile metadata cached on registration');
  }

  return {
    user: data.user,
    profileData: {
      fullName,
      phoneNumber,
      businessType,
    },
  };
}

export async function signOut() {
  const { error } = await supabase.auth.signOut();

  // Full data wipe on logout
  try {
    await clearSessionCache();
    await clearProfileCache();
    await wipeDatabase();
    await AsyncStorage.clear();
  } catch (e) {
    console.error("Error wiping local data during logout:", e);
  }

  if (error) {
    throw error;
  }
}

/**
 * Initiates password reset process.
 * Supabase will generate a recovery token and send it via the 'Send Email' auth hook.
 */
export async function forgotPassword(email: string) {
  const { data, error } = await supabase.auth.resetPasswordForEmail(email, {
    redirectTo: undefined, // Let the app handle it instead of deep links
  });

  if (error) {
    throw error;
  }

  return data;
}

/**
 * Updates the password for the current session user.
 */
export async function updatePassword(newPassword: string) {
  const { data, error } = await supabase.auth.updateUser({
    password: newPassword,
  });

  if (error) {
    throw error;
  }

  return data;
}